###################### Metricbeat Configuration Example #######################

# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/metricbeat/index.html

# =========================== Modules configuration ============================

metricbeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

# ================================== General ===================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name:

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["cw-automate"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging

# ================================== Outputs ===================================

# Configure what output to use when sending the data collected by the beat.

#================================ Custom Perch Output ============================

output.elasticsearch:
  hosts: ["ingest.perchsecurity.com:443/elastic"]
#  headers:
#    X-Perch-Header: "${perch-client-token}"
  protocol: "https"

# ================================= Processors =================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
