# Module: sql
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.8/metricbeat-module-sql.html
# userauthlockoutstats table - auth events are 5 hours off for me. May need adjusting for you.
# PS

- module: sql
  metricsets:
    - query
  period: 1m
  hosts: ["${perch-read-only-sql-user}:${perch-read-only-sql-pass}@tcp(${sql-server-ip}:${sql-server-port})/${sql-server-db}"]
  
  driver: "mysql"   
  sql_query: "select concat("auth") as automate_source, concat("event") as automate_event_type, userauthenticationlockoutstats.* from userauthenticationlockoutstats where UpdateDate >= DATE_SUB(DATE_SUB(now(), INTERVAL 1 MINUTE), INTERVAL -5 HOUR)"
  sql_response_format: table
